apiVersion: apps/v1
kind: Deployment
metadata:
  name: hongbao
  namespace: app-office
  labels:
    app: hongbao
spec:
  selector:
    matchLabels:
      app: hongbao
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hongbao
    spec:
      containers:
        - name: hongbao
          image: 'registry-intl.cn-shanghai.aliyuncs.com/hippy/hongbao:latest'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081
          resources:
            limits:
              cpu: "1800m"
              memory: "2Gi"
            requests:
              cpu: "1200m"
              memory: "1500Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: hongbao-service
  namespace: app-office
  labels:
    name: hongbao-service
spec:
  type: NodePort
  ports:
  - name: hongbao
    port: 8081
    targetPort: 8081
    nodePort: 30091
  selector:
    app: hongbao
