server:
  port: 8081
  servlet:
    context-path: /app
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  # ======mysql datasource config
  datasource:
    # 数据源名称
    name: jy_datasource
    # 数据源类型：阿里巴巴druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 连接数据库的驱动程序
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 基本属性，链接，用户/密码
      url: jdbc:mysql://192.168.177.18:3306/juneyao_party_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: luocheng
      password: 1qaz@WSX
      # 配置连接池初始化大小/最小/最大
      initial-size: 5
      min-idle: 5
      max-active: 100
      #获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 检查空闲连接是否有效
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      log-abandoned: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    cluster:
      nodes: 192.168.177.1:6379
    password: hongbao
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
# ======mybatis的映射文件和java的bean对象的位置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.juneyao.activity.dao.entity.*

imfUrl:
  # Extranet_param：外网名称 Intranet_param：内网名称
  Extranet_param: http://121.46.238.133:8000/
  Intranet_param: http://192.168.177.44:8090/

file:
  host: 192.168.177.9
  userName: junyao_sftp
  passWord: junyao_sftp
  port: 22
  basePath: /home/hongbao/deployment/file/
  sftpPath: data/
  imageUrl: http://192.168.177.44:8090/data

junyao:
  url: http://192.168.177.61:30081/jery/user/confirmUser