spring:
  datasource-tcmp:
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:oracle:thin:@192.168.32.107:1521:cdb
      username: tcmp1
      password: tcmp1
      driver-class-name: oracle.jdbc.driver.OracleDriver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      sql-script-encoding: UTF-8
bosc:
  #报文版本号
  msgVerNo: V1.0
  #支付报文版本号
  payMsgVerNo: V2.0
  #渠道编码
  channelID: "06368989"
  #请求地址api
  reqUrl: http://192.168.32.193:18080/api
  #3des Key
  desKey: jr1wNqGI5c2Yr2kXYH4DuRiu
  #rsa签名密钥对
  rsa:
    privateKeyFilePath: /home/ajxt/deployment/payCenter/config/boc/pkcs8_private_key.pem        #C:\Users\Administrator\Desktop\rsa\pkcs8_private_key.pem
    publicKeyFilePath: /home/ajxt/deployment/payCenter/config/boc/public_key.pem #C:\Users\Administrator\Desktop\rsa\public_key.pem

imgUrl:
  # 文件查看地址
  certificationImgPath: http://192.168.32.143:18099/file

# 支付中心接口地址
payCenter:
  # 冻结解冻
  freezeOrUnfreeze: http://192.168.64.59:9066/api/trade/shbank/freezeOrUnfreeze
  # 销户
  cancellation: http://192.168.64.59:9066/api/account/shbank/cancellation
  # 开户
  customerOpen: http://192.168.64.59:9066/api/account/shbank/customerOpen
  # 产品开户
  productOpen: http://192.168.64.59:9066/api/account/shbank/productOpen
  # 挂账入金
  dealOnAccountMoney: http://192.168.64.59:9066/api/trade/shbank/dealOnAccountMoney
  # 钱包提现
  cashOut: http://192.168.64.59:9066/api/trade/shbank/cashOut
  # 普通支付
  normalPay: http://192.168.64.59:9066/api/trade/shbank/normalPay
  # 产品成立清分
  clearing: http://192.168.64.59:9066/api/trade/shbank/clearing
  # 变更绑定卡
  bindBankCard: http://192.168.64.59:9066/api/account/shbank/bindBankCard
  # 查询余额
  balanceQuery: http://192.168.64.59:9066/api/query/shbank/balanceQuery
  # 查询单笔交易状态
  tradeStatusQuery: http://192.168.64.59:9066/api/query/shbank/tradeStatusQuery
  # 查询账簿开立状态
  accCreateStatusQuery: http://192.168.64.59:9066/api/query/shbank/accCreateStatusQuery
  # 登录
  login: http://192.168.64.59:8033/oauth/login
  # 登录用户密码修改
  loginEdit: http://192.168.64.59:8033/oauth/system/user/password/edit
  # 产品列表
  prodName: http://192.168.64.59:9066/api/query/tcmp/queryTrustPlanInfo
  # 赎回分红、分配划款
  redeemTransferMoney: http://192.168.64.59:9066/api/trade/shbank/redeemTransferMoney
# APP接口地址
appInterface:
  # 产品列表
  prodName: http://192.168.64.59:9099/appdev/mcrm/saleProdCaseQuery

#批量使用参数
job:
  #回款文件远程参数
  sftp:
    app:
      address: 192.168.32.143
      port: 22
      userName: ph_sftp
      password: 123456
      sftpPath: /upload/file/ajxtpay

#财富账户后管使用参数
management:
  localhost: /home/ajxt/deployment/payCenter/payManage/changeCardFile/
  #文件上传
  sftp:
    manage:
      address: 192.168.32.143
      port: 22
      userName: ph_sftp
      password: 123456
      sftpPath: /public/file/ajxtmanage

appNoticeUrl:
  # app通知url,结尾不用/
  #url: http://192.168.64.59:9099/appdev
  url: http://192.168.59.235:9099/appdev
  #url: http://192.168.59.20:9099/appdev

thirdtrade:
  sendSmsUrl: http://192.168.32.193:8033/sms/sendSms/singleSms
