---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-deploy
  namespace: junyao
spec:
  replicas: 2
  minReadySeconds: 5 # Wait 5 seconds after each new pod comes up before marked as "ready"
  strategy:
    type: RollingUpdate # describe how we do rolling updates
    rollingUpdate:
      maxUnavailable: 1 # When updating take one pod down at a time
      maxSurge: 1
  selector:
    matchLabels:
      name: hellogo-app
  template:
    metadata:
      labels:
        name: hellogo-app
    spec:
      containers:
      - name: hellogo
        image: sjwayrhz/hellogo:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hellogo-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30001
  selector:
    name: hellogo-app