apiVersion: v1
kind: ConfigMap
metadata:
  name:  dev-api-config
  namespace: app-dev
data:
  api-env: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  dev-api-pvc
  namespace: app-dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dev-api
  namespace: app-dev
  labels:
    app:  dev-api
spec:
  selector:
    matchLabels:
      app:  dev-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  dev-api
    spec:
      containers:
        - name:  dev-api
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-api:202108311631'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(api-env-key)"]
          ports:
          - containerPort: 8081 
          env:
          - name: api-env-key
            valueFrom:
              configMapKeyRef:
                name:  dev-api-config
                key: api-env 
          resources:
            limits:
              cpu: "800m"
              memory: "2Gi"
            requests:
              cpu: "400m"
              memory: "1Gi" 
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName:  dev-api-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  dev-api-service
  namespace: app-dev
  labels:
    name:  dev-api-service
spec:
  type: NodePort
  ports:
  - name:  dev-api
    port: 8081
    targetPort: 8081
    nodePort: 30082
  selector:
    app:  dev-api
