---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yun-web
  namespace: app-prod
  labels:
    app: yun-web
spec:
  selector:
    matchLabels:
      app: yun-web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yun-web
    spec:
      containers:
        - name: yun-web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/yun-web:1.0'
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP   
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: yun-web-service
  namespace: app-prod
  labels:
    name: yun-web-service
spec:
  type: NodePort
  ports:
  - name: yun-web
    port: 8080
    targetPort: 8080
    nodePort: 30064
  selector:
    app: yun-web