---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yun-web
  namespace: app-caobo
  labels:
    app: yun-web
spec:
  selector:
    matchLabels:
      app: yun-web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yun-web
    spec:
      containers:
        - name: yun-web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/caobo-web:202108251155'
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP   
          resources:
            limits:
              cpu: "800m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi" 
---
apiVersion: v1
kind: Service
metadata:
  name: yun-web-service
  namespace: app-caobo
  labels:
    name: yun-web-service
spec:
  type: NodePort
  ports:
  - name: yun-web
    port: 8080
    targetPort: 8080
    nodePort: 30084
  selector:
    app: yun-web
