

#office环境
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-office
data:
  vue.conf: |-
    upstream vue{
      server 10.230.7.20:30088;
    }
    
    server {
      listen  8083;
      server_name localhost;
    
      location / {
        root /usr/share/nginx/html; 
        index  index.html;
      }
      
      location /juneyao {
        proxy_pass http://vue;
      }
    }
  


#dev环境

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-dev
data:
  vue.conf: |-
    upstream vue{
      server 192.168.177.35:30084;
    }
    
    server {
      listen  8083;
      server_name localhost;
    
      location / {
        root /usr/share/nginx/html; 
        index  index.html;
      }
      
      location /juneyao {
        proxy_pass http://vue;
      }
    }
 
 
 
 
 
#prod环境

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-prod
data:
  vue.conf: |-
    upstream vue{
      server 192.168.177.35:30082;
    }
    
    server {
      listen  8083;
      server_name localhost;
    
      location / {
        root /usr/share/nginx/html; 
        index  index.html;
      }
      
      location /juneyao {
        proxy_pass http://vue;
      }
    }
  