kind: Service
apiVersion: v1
metadata:
  name: vue
  namespace: app-office
spec:
  selector:
    app: vue
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
      nodePort: 30086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: app-office
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: vue
  replicas: 1
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: registry.cn-shanghai.aliyuncs.com/jyjt/develop-vue:0.0.1
          ports:
          - name: http
            containerPort: 8083
          volumeMounts:
          - name: vueconf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
      volumes:
      - name: vueconf
        configMap:
          name: vue-config