apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-web-config
  namespace: app-dev
data:
  web-env: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web
  namespace: app-dev
  labels:
    app: dev-web
spec:
  selector:
    matchLabels:
      app: dev-web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
        - name: dev-web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-web:202108301436'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(web-env-key)"]
          ports:
          - containerPort: 8080 
          env:
          - name: web-env-key
            valueFrom:
              configMapKeyRef:
                name: dev-web-config
                key: web-env 
          resources:
            limits:
              cpu: "3000m"
              memory: "8Gi"
            requests:
              cpu: "1500m"
              memory: "4Gi" 
---
apiVersion: v1
kind: Service
metadata:
  name: dev-web-service
  namespace: app-dev
  labels:
    name: dev-web-service
spec:
  type: NodePort
  ports:
  - name: dev-web
    port: 8080
    targetPort: 8080
    nodePort: 30084
  selector:
    app: dev-web
