apiVersion: v1
kind: Service
metadata:
  name: kiali-nodeport
  namespace: istio-system
  labels:
    app: kiali
spec:
  type: NodePort
  ports:
  - name: http
    port: 20001
    targetPort: 20001
    nodePort: 30021
  - name: http-metrics
    port: 9090
    targetPort: 9090
    nodePort: 30023
  selector:
    app: kiali