apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap-3
data:
  DEPLOYMENT_ENV: test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-configmap-3-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hwy-3
  labels:
    app: demo-hwy-3
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-hwy-3
  template:
    metadata:
      labels:
        app: demo-hwy-3
    spec:
      containers:
      - name: demo
        image: registry.cn-shanghai.aliyuncs.com/taoistmonk/images:huwanyang168-demo
        imagePullPolicy: IfNotPresent
        args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOYMENT_ENV_KEY
          valueFrom:
            configMapKeyRef:
              name: demo-configmap-3
              key: DEPLOYMENT_ENV
        volumeMounts:
          - name: nfs
            mountPath: /mnt
      volumes:
        - name: nfs
          persistentVolumeClaim: 
            claimName: demo-configmap-3-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: demo-hwy-3
  labels:
    app: demo-hwy-3
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32125
  selector:
    app: demo-hwy-3     
