apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap-2
data:
  DEPLOYMENT_ENV: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hwy-2
  labels:
    app: demo-hwy-2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-hwy-2
  template:
    metadata:
      labels:
        app: demo-hwy-2
    spec:
      containers:
      - name: demo
        image: registry.cn-shanghai.aliyuncs.com/taoistmonk/images:huwanyang168-demo
        imagePullPolicy: IfNotPresent
        args: ["--spring.profiles.active=$(DEPLOYMENT_ENV_KEY)"]
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOYMENT_ENV_KEY
          valueFrom:
            configMapKeyRef:
              name: demo-configmap-2
              key: DEPLOYMENT_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: demo-hwy-2
  labels:
    app: demo-hwy-2
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32124
  selector:
    app: demo-hwy-2     
