apiVersion: v1
kind: ConfigMap
metadata:
  name: office-api-config
  namespace: app-office
data:
  api-env: office
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-api-pvc
  namespace: app-office
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-api
  namespace: app-office
  labels:
    app: office-api
spec:
  selector:
    matchLabels:
      app: office-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: office-api
    spec:
      containers:
        - name: office-api
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-api:202108311631'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(api-env-key)"]
          ports:
          - containerPort: 8081 
          env:
          - name: api-env-key
            valueFrom:
              configMapKeyRef:
                name: office-api-config
                key: api-env 
          resources:
            limits:
              cpu: "800m"
              memory: "2Gi"
            requests:
              cpu: "400m"
              memory: "1Gi" 
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: office-api-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: office-api-service
  namespace: app-office
  labels:
    name: office-api-service
spec:
  type: NodePort
  ports:
  - name: office-api
    port: 8081
    targetPort: 8081
    nodePort: 30086
  selector:
    app: office-api
