apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-dev
data:
  vue.conf: |-
    upstream vue{
      server 192.168.177.35:30085;
    }
    
    server {
      listen  8083;
      server_name localhost;
      access_log /var/log/nginx/vue_access_log main;
    
      location / {
        root /usr/share/nginx/html; 
        try_files $uri $uri/ index.html;
      }
      
      location /juneyao {
        proxy_pass http://vue;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImRHRnZhWE4wYlc5dWEwQXhOak11WTI5dE9sWjNkalUyZEhrMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vue-pvc
  namespace: app-dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
kind: Service
apiVersion: v1
metadata:
  name: vue
  namespace: app-dev
spec:
  selector:
    app: vue
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
      nodePort: 30086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: app-dev
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: vue
  replicas: 2
  template:
    metadata:
      labels:
        app: vue
    spec:
      imagePullSecrets: 
        - name: registry-pull-secret
      containers:
        - name: vue
          image: registry.cn-shanghai.aliyuncs.com/jyjt/office-vue:202109160810
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
          - name: http
            containerPort: 8083
          volumeMounts:
          - name: vueconf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
          - name: vuelog
            mountPath: /var/log/nginx/
      volumes:
      - name: vueconf
        configMap:
          name: vue-config
      - name: vuelog
        persistentVolumeClaim:
          claimName: vue-pvc