apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-web-config
  namespace: app-dev
data:
  web-env: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-web-pvc
  namespace: app-dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web
  namespace: app-dev
  labels:
    app: dev-web
spec:
  selector:
    matchLabels:
      app: dev-web
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
        - name: dev-web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-web:202108301436'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(web-env-key)"]
          ports:
          - containerPort: 8080 
          env:
          - name: web-env-key
            valueFrom:
              configMapKeyRef:
                name: dev-web-config
                key: web-env 
          resources:
            limits:
              cpu: "1800m"
              memory: "4Gi"
            requests:
              cpu: "1200m"
              memory: "2Gi" 
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: dev-web-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dev-web-service
  namespace: app-dev
  labels:
    name: dev-web-service
spec:
  type: NodePort
  ports:
  - name: dev-web
    port: 8080
    targetPort: 8080
    nodePort: 30084
  selector:
    app: dev-web
