apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: app-dev
data:
  web-env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImRHRnZhWE4wYlc5dWEwQXhOak11WTI5dE9sWjNkalUyZEhrMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: app-dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app-dev
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-web:202109101447'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(web-env-key)"]
          ports:
          - containerPort: 8082 
          env:
          - name: web-env-key
            valueFrom:
              configMapKeyRef:
                name: web-config
                key: web-env 
          startupProbe:
            httpGet:
              path: /
              port: 8082
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8082
            initialDelaySeconds: 40
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          resources:
            limits:
              cpu: "1800m"
              memory: "2Gi"
            requests:
              cpu: "1200m"
              memory: "1500Mi" 
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: web-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app-dev
  labels:
    name: web-service
spec:
  type: NodePort
  ports:
  - name: web
    port: 8082
    targetPort: 8082
    nodePort: 30085
  selector:
    app: web
