apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: app-office
data:
  web-env: office
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: app-office
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app-office
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-web:202109020732'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(web-env-key)"]
          ports:
          - containerPort: 8080 
          env:
          - name: web-env-key
            valueFrom:
              configMapKeyRef:
                name: web-config
                key: web-env 
          resources:
            limits:
              cpu: "1500m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi" 
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 100
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8080
            initialDelaySeconds: 120
            failureThreshold: 5
            periodSeconds: 10
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: web-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app-office
  labels:
    name: web-service
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30088
  selector:
    app: web
