apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-office
data:
  vue-env: office
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vue-pvc
  namespace: app-office
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: app-office
  labels:
    app: vue
spec:
  selector:
    matchLabels:
      app: vue
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: 'registry.cn-shanghai.aliyuncs.com/jyjt/develop-vue:202109050945'
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(vue-env-key)"]
          ports:
          - containerPort: 8083
          env:
          - name: vue-env-key
            valueFrom:
              configMapKeyRef:
                name: vue-config
                key: vue-env 
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 25
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /#/login
              port: 8083
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "50Mi" 
          volumeMounts: 
            - name: nfs
              mountPath: /var/log/nginx
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: vue-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
  namespace: app-office
  labels:
    name: vue-service
spec:
  type: NodePort
  ports:
  - name: vue
    port: 8083
    targetPort: 8083
    nodePort: 30089
  selector:
    app: vue
