apiVersion: v1
kind: ConfigMap
metadata:
  name: vue-config
  namespace: app-prod
data:
  vue.conf: |-
    upstream vue{
      server 192.168.177.35:30083;
    }
    
    server {
      listen  8083;
      server_name localhost;
    
      location / {
        root /usr/share/nginx/html; 
        index  index.html;
      }
      
      location /juneyao {
        proxy_pass http://vue;
      }
    }
---
kind: Service
apiVersion: v1
metadata:
  name: vue
  namespace: app-prod
spec:
  selector:
    app: vue
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
      nodePort: 30085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: app-prod
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: vue
  replicas: 2
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: registry.cn-shanghai.aliyuncs.com/jyjt/develop-vue:0.0.1
          ports:
          - name: http
            containerPort: 8083
          volumeMounts:
          - name: vueconf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
      volumes:
      - name: vueconf
        configMap:
          name: vue-config